### PR TITLE
NEW: Added sorting for servers

### LINKED ISSUE #44: Allow to order servers
- Hostname
- Uptime
- RAM Usage
- Disk Usage

And save it for the user preference!

### PR DESCRIPTION
**Pull request by venarius**
Added sorting to servers

Screenshot from 2019-04-11 20-52-58

Closes #44

### CODE REVIEW

**Comment by venarius** [comment]
Also, have you thought about moving this project to an organization? It gives a lot of bonuses to open source projects and would have a cool name like "sssm/sssm" 🤗

**Comment by fbocolowski** [comment]
That would be nice! "sssm" username is alredy taken =/

**Comment by venarius** [comment]
@fbocolowski I sent an email to github support and kindly asked them to remove / rename that inactive organization currently occupying the name 🙂

**Comment by fbocolowski** [comment]
Great! Let me know if anything.

**Pull request merged**
